version: '3.9'
services:
  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: keycloak
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - 5050:80

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: database
      DB_DATABASE: keycloak
      DB_USER: docker
      DB_SCHEMA: public
      DB_PASSWORD: 1234
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 1234
    ports: 
      - 8081:8080    
    depends_on:
      - mailhog

  # user-service:
  #   container_name: user-service
  #   build:
  #     context: .
  #     dockerfile: Api/TestDockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - Database__Host=jfdi_test_db
  #     - Database__User=docker
  #     - Database__Password=secret
  #     - Database__InitialCatalog=jfdi_db
  #     - Database__Port=5432
  #     - Keycloak__ClientId=project-management-api
  #     - Keycloak__AppClientId=project-management-api
  #     - Keycloak__ClientSecret=97b28e69-f699-46a6-bb24-ee0a24db84d6
  #     - Keycloak__Audience=account
  #     - Keycloak__Realm=JFDI
  #     - Keycloak__BaseUrl=http://keycloak:8080/
  #     - Keycloak__RedirectUrl=https://fakedomain.com/USER_ID/register
  #   depends_on: 
  #    - keycloak
  #   ports: 
  #     - 8094:80
  #     - 8095:443
  #     - 8096:5000
  #     - 8097:5001
  
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    depends_on:
      - database
