version: '3.9'
services:
  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: keycloak
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - 5050:80

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: database
      DB_DATABASE: keycloak
      DB_USER: docker
      DB_SCHEMA: public
      DB_PASSWORD: 1234
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 1234
    ports: 
      - 8081:8080    
    depends_on:
      - mailhog
  
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports: 
      - 8025:8025
    depends_on:
      - database

  redis:
    image: redis

  sentry:
    image: sentry
    links:
     - redis
     - database
    ports:
     - 9000:9000
    environment:
      SENTRY_SECRET_KEY: '12341234123412341234123412341234'
      SENTRY_POSTGRES_HOST: database
      SENTRY_DB_USER: docker
      SENTRY_DB_PASSWORD: 1234
      SENTRY_REDIS_HOST: redis

  cron:
    image: sentry
    links:
     - redis
     - database
    command: "sentry run cron"
    environment:
      SENTRY_SECRET_KEY: '12341234123412341234123412341234'
      SENTRY_POSTGRES_HOST: database
      SENTRY_DB_USER: docker
      SENTRY_DB_PASSWORD: 1234
      SENTRY_REDIS_HOST: redis

  worker:
    image: sentry
    links:
     - redis
     - database
    command: "sentry run worker"
    environment:
      SENTRY_SECRET_KEY: '12341234123412341234123412341234'
      SENTRY_POSTGRES_HOST: database
      SENTRY_DB_USER: docker
      SENTRY_DB_PASSWORD: 1234
      SENTRY_REDIS_HOST: redis